"""
HYPERVOID 速查表模块 - Git/Docker/NPM/Regex/Python/VSCode/Markdown/Linux/K8S/PowerShell
"""
import os, msvcrt
from rich.console import Console
from rich.text import Text
from rich.align import Align
from rich.rule import Rule

console = Console()

class T:
    CYAN='bold bright_cyan'; MAG='bold bright_magenta'; YEL='bold bright_yellow'
    GRN='bold bright_green'; RED='bold bright_red'; WHT='bold bright_white'
    ACCENT='bold bright_magenta'; DIM='dim bright_white'; OK='bold bright_green'
    WARN='bold bright_yellow'; KEY='bold bright_yellow'; LABEL='bold bright_white'
    DESC='dim bright_white'

def read_key():
    ch = msvcrt.getch()
    if ch == b'\r': return ('enter','')
    if ch == b'\x1b': return ('esc','')
    if ch == b'\x03': raise KeyboardInterrupt
    if ch in (b'\x00', b'\xe0'):
        ch2 = msvcrt.getch()
        m = {b'H':'up',b'P':'down',b'I':'pgup',b'Q':'pgdn'}
        return ('nav', m.get(ch2,''))
    return ('char', ch.decode('utf-8',errors='ignore').lower())

def clear(): os.system('cls')

def scroll_view(title, lines):
    pos = 0
    page = max(console.height - 10, 8)
    while True:
        clear()
        console.print(Align.center(Text(f"  ═══  {title}  ═══  ", style=T.ACCENT)))
        console.print()
        visible = lines[pos:pos+page]
        for line in visible:
            if isinstance(line, Text):
                console.print(f"  {line}")
            else:
                console.print(f"  {line}")
        total = len(lines)
        if total > page:
            pct = int(pos/max(1,total-page)*100)
            bar_len = 40
            filled = int(bar_len*pos/max(1,total-page))
            bar = '█'*filled + '░'*(bar_len-filled)
            console.print(f"\n  [{T.DIM}]  {bar}  {pct}%[/]")
        console.print(f"  [{T.DIM}]↑↓ 滚动  PgUp/PgDn 翻页  Esc 返回[/]")
        kt,k = read_key()
        if kt=='esc' or (kt=='char' and k=='q'): return
        if kt=='nav':
            if k=='up' and pos>0: pos-=1
            if k=='down' and pos<max(0,total-page): pos+=1
            if k=='pgup': pos=max(0,pos-page)
            if k=='pgdn': pos=min(max(0,total-page),pos+page)

def fmt(data):
    lines = []
    for item in data:
        if len(item)==3 and item[2]=='h':
            lines.append(Text(f"\n  {item[0]}", style=T.ACCENT))
        else:
            t = Text()
            t.append(f"  {item[0]:<36}", style=T.GRN)
            t.append(item[1], style=T.DESC)
            lines.append(t)
    return lines

# ── Git 速查 ──────────────────────────────────────────────
GIT = [
    ('基础操作','h'),
    ('git init','初始化新仓库'),
    ('git clone <url>','克隆远程仓库'),
    ('git clone --depth 1 <url>','浅克隆(只取最新提交)'),
    ('git add .','添加所有更改到暂存区'),
    ('git add <file>','添加指定文件'),
    ('git add -p','交互式暂存(逐块选择)'),
    ('git commit -m "msg"','提交暂存区'),
    ('git commit -am "msg"','添加并提交已跟踪文件'),
    ('git commit --amend','修改上次提交'),
    ('git status','查看工作区状态'),
    ('git status -s','简洁状态'),
    ('git diff','查看未暂存的更改'),
    ('git diff --staged','查看已暂存的更改'),
    ('git diff branch1..branch2','比较两个分支'),
    ('分支管理','h'),
    ('git branch','列出本地分支'),
    ('git branch -a','列出所有分支(含远程)'),
    ('git branch <name>','创建新分支'),
    ('git branch -m <old> <new>','重命名分支'),
    ('git checkout <branch>','切换分支'),
    ('git checkout -b <branch>','创建并切换分支'),
    ('git switch <branch>','切换分支(推荐)'),
    ('git switch -c <branch>','创建并切换(推荐)'),
    ('git merge <branch>','合并指定分支'),
    ('git merge --no-ff <branch>','合并(保留合并记录)'),
    ('git branch -d <branch>','删除已合并分支'),
    ('git branch -D <branch>','强制删除分支'),
    ('远程操作','h'),
    ('git remote -v','查看远程仓库'),
    ('git remote add origin <url>','添加远程仓库'),
    ('git remote set-url origin <url>','修改远程地址'),
    ('git push origin <branch>','推送到远程'),
    ('git push -u origin <branch>','推送并设置上游'),
    ('git push --force-with-lease','安全强制推送'),
    ('git pull','拉取远程更新'),
    ('git pull --rebase','变基拉取'),
    ('git fetch','获取远程更新(不合并)'),
    ('git fetch --prune','获取并清理已删除远程分支'),
    ('撤销操作','h'),
    ('git restore <file>','丢弃工作区更改(推荐)'),
    ('git restore --staged <file>','取消暂存(推荐)'),
    ('git reset HEAD <file>','取消暂存'),
    ('git checkout -- <file>','丢弃工作区更改'),
    ('git reset --soft HEAD~1','撤销上次提交(保留更改)'),
    ('git reset --mixed HEAD~1','撤销提交(保留工作区)'),
    ('git reset --hard HEAD~1','撤销上次提交(丢弃更改)'),
    ('git revert <commit>','创建反向提交'),
    ('git stash','暂存当前更改'),
    ('git stash pop','恢复暂存更改'),
    ('git stash list','列出所有暂存'),
    ('git stash drop','删除最近的暂存'),
    ('git stash apply stash@{0}','应用指定暂存'),
    ('git stash -u','暂存(含未跟踪文件)'),
    ('Cherry-pick','h'),
    ('git cherry-pick <commit>','拣选单个提交'),
    ('git cherry-pick A..B','拣选范围提交'),
    ('git cherry-pick --no-commit <commit>','拣选但不自动提交'),
    ('变基 Rebase','h'),
    ('git rebase <branch>','变基到指定分支'),
    ('git rebase -i HEAD~3','交互式变基(合并/编辑提交)'),
    ('git rebase --abort','中止变基'),
    ('git rebase --continue','解决冲突后继续变基'),
    ('工作树 Worktree','h'),
    ('git worktree add <path> <branch>','添加工作树'),
    ('git worktree list','列出工作树'),
    ('git worktree remove <path>','删除工作树'),
    ('二分查找 Bisect','h'),
    ('git bisect start','开始二分查找'),
    ('git bisect bad','标记当前为坏提交'),
    ('git bisect good <commit>','标记为好提交'),
    ('git bisect reset','结束二分查找'),
    ('日志查看','h'),
    ('git log','查看提交日志'),
    ('git log --oneline','简洁日志'),
    ('git log --graph','图形化分支日志'),
    ('git log -p -5','最近5次提交的diff'),
    ('git log --author="name"','按作者过滤'),
    ('git log --since="2025-01-01"','按日期过滤'),
    ('git shortlog -sn','提交统计'),
    ('git blame <file>','查看文件每一行的修改者'),
    ('标签管理','h'),
    ('git tag <name>','创建轻量标签'),
    ('git tag -a v1.0 -m "msg"','创建附注标签'),
    ('git tag -d <name>','删除本地标签'),
    ('git push origin --tags','推送所有标签'),
    ('git push origin :refs/tags/<name>','删除远程标签'),
]

# ── Docker 速查 ───────────────────────────────────────────
DOCKER = [
    ('容器操作','h'),
    ('docker run -d <image>','后台运行容器'),
    ('docker run -it <image> /bin/bash','交互式运行'),
    ('docker run -p 8080:80 <image>','端口映射'),
    ('docker run --name <name> <image>','指定容器名'),
    ('docker run --rm <image>','运行后自动删除'),
    ('docker run -e KEY=VAL <image>','设置环境变量'),
    ('docker run --memory=512m <image>','限制内存'),
    ('docker run --cpus=1.5 <image>','限制CPU'),
    ('docker run --network=host <image>','使用主机网络'),
    ('docker ps','列出运行中的容器'),
    ('docker ps -a','列出所有容器'),
    ('docker ps -q','只输出容器ID'),
    ('docker stop <id>','停止容器'),
    ('docker start <id>','启动已停止的容器'),
    ('docker restart <id>','重启容器'),
    ('docker rm <id>','删除容器'),
    ('docker rm -f <id>','强制删除运行中容器'),
    ('docker logs <id>','查看容器日志'),
    ('docker logs -f <id>','实时查看日志'),
    ('docker logs --tail 100 <id>','查看最后100行日志'),
    ('docker exec -it <id> /bin/bash','进入容器'),
    ('docker exec -it <id> sh','进入容器(sh)'),
    ('docker inspect <id>','查看容器详情'),
    ('docker stats','实时资源监控'),
    ('docker top <id>','查看容器进程'),
    ('镜像操作','h'),
    ('docker images','列出镜像'),
    ('docker pull <image>','拉取镜像'),
    ('docker push <image>','推送镜像'),
    ('docker build -t <name> .','构建镜像'),
    ('docker build -f Dockerfile.dev -t <name> .','指定Dockerfile构建'),
    ('docker build --no-cache -t <name> .','无缓存构建'),
    ('docker rmi <image>','删除镜像'),
    ('docker image prune','清理无用镜像'),
    ('docker image prune -a','清理所有无用镜像'),
    ('docker tag <src> <dst>','镜像打标签'),
    ('docker save -o img.tar <image>','导出镜像'),
    ('docker load -i img.tar','导入镜像'),
    ('数据卷','h'),
    ('docker volume ls','列出数据卷'),
    ('docker volume create <name>','创建数据卷'),
    ('docker volume rm <name>','删除数据卷'),
    ('docker volume prune','清理未使用数据卷'),
    ('docker run -v /host:/container','挂载目录'),
    ('docker run -v vol:/container','命名卷挂载'),
    ('docker run --mount type=bind,src=.,dst=/app','绑定挂载'),
    ('Docker Compose','h'),
    ('docker-compose up','启动所有服务'),
    ('docker-compose up -d','后台启动'),
    ('docker-compose up --build','重建并启动'),
    ('docker-compose down','停止并删除'),
    ('docker-compose down -v','停止并删除(含数据卷)'),
    ('docker-compose ps','查看服务状态'),
    ('docker-compose logs','查看日志'),
    ('docker-compose logs -f <svc>','实时查看指定服务日志'),
    ('docker-compose exec <svc> sh','进入服务容器'),
    ('docker-compose restart <svc>','重启指定服务'),
    ('docker-compose pull','拉取最新镜像'),
    ('Dockerfile 最佳实践','h'),
    ('FROM <image> AS builder','多阶段构建命名'),
    ('COPY --from=builder /out /app','从构建阶段复制'),
    ('RUN apk add --no-cache <pkg>','不缓存安装(Alpine)'),
    ('COPY . . (放在末尾)','利用构建缓存层'),
    ('HEALTHCHECK CMD curl ...','健康检查'),
    ('WORKDIR /app','设置工作目录'),
    ('EXPOSE 80','声明端口'),
    ('USER node','切换非root用户'),
    ('网络','h'),
    ('docker network ls','列出网络'),
    ('docker network create <name>','创建网络'),
    ('docker network connect <net> <ctr>','连接容器到网络'),
    ('docker network disconnect <net> <ctr>','断开网络'),
    ('docker network rm <name>','删除网络'),
]

# ── NPM 速查 ──────────────────────────────────────────────
NPM = [
    ('包管理 - npm','h'),
    ('npm install <pkg>','安装包'),
    ('npm install <pkg>@<ver>','安装指定版本'),
    ('npm install <pkg> -g','全局安装'),
    ('npm install <pkg> -D','安装为开发依赖'),
    ('npm install','安装所有依赖'),
    ('npm ci','CI 模式安装(精确锁定)'),
    ('npm uninstall <pkg>','卸载包'),
    ('npm update','更新所有包'),
    ('npm outdated','检查过期包'),
    ('npm list','列出已安装包'),
    ('npm list -g --depth=0','列出全局包(一级)'),
    ('npm audit','安全审计'),
    ('npm audit fix','自动修复漏洞'),
    ('npm version <major|minor|patch>','升级版本号'),
    ('包管理 - pnpm','h'),
    ('pnpm install','安装所有依赖'),
    ('pnpm add <pkg>','安装包'),
    ('pnpm add -D <pkg>','安装为开发依赖'),
    ('pnpm remove <pkg>','卸载包'),
    ('pnpm update','更新所有包'),
    ('pnpm dlx <command>','临时执行(= npx)'),
    ('pnpm store status','检查存储状态'),
    ('pnpm store prune','清理存储'),
    ('脚本运行','h'),
    ('npm run <script>','运行脚本'),
    ('npm start','运行 start 脚本'),
    ('npm test','运行 test 脚本'),
    ('npm run build','运行 build 脚本'),
    ('npm run dev','运行 dev 脚本'),
    ('npm run <script> -- --flag','传递参数到脚本'),
    ('npx <command>','临时执行命令'),
    ('npx create-react-app <name>','创建React项目'),
    ('npx ts-node <file>','运行TypeScript文件'),
    ('配置','h'),
    ('npm init','初始化 package.json'),
    ('npm init -y','快速初始化'),
    ('npm config list','查看配置'),
    ('npm config set <key> <val>','设置配置'),
    ('npm config get registry','查看仓库地址'),
    ('npm cache clean --force','清理缓存'),
    ('npm publish','发布包'),
    ('npm pack','打包为 tgz'),
    ('package.json scripts','h'),
    ('"preinstall": "cmd"','安装前自动运行'),
    ('"postinstall": "cmd"','安装后自动运行'),
    ('"prebuild": "cmd"','构建前自动运行'),
    ('"watch": "nodemon src"','文件监听'),
    ('"lint": "eslint src"','代码检查'),
    ('"typecheck": "tsc --noEmit"','类型检查'),
    ('Yarn 对照','h'),
    ('yarn add <pkg>','= npm install <pkg>'),
    ('yarn add -D <pkg>','= npm install -D <pkg>'),
    ('yarn remove <pkg>','= npm uninstall <pkg>'),
    ('yarn run <script>','= npm run <script>'),
    ('yarn dlx <cmd>','= npx <cmd>'),
    ('yarn why <pkg>','查看依赖关系'),
]

# ── 正则表达式速查 ────────────────────────────────────────
REGEX = [
    ('基础语法','h'),
    ('.','匹配任意字符(除换行)'),
    ('\\d','匹配数字 [0-9]'),
    ('\\D','匹配非数字'),
    ('\\w','匹配单词字符 [a-zA-Z0-9_]'),
    ('\\W','匹配非单词字符'),
    ('\\s','匹配空白字符'),
    ('\\S','匹配非空白字符'),
    ('量词','h'),
    ('*','零次或多次(贪婪)'),
    ('+','一次或多次(贪婪)'),
    ('?','零次或一次'),
    ('*?','零次或多次(懒惰)'),
    ('+?','一次或多次(懒惰)'),
    ('{n}','恰好 n 次'),
    ('{n,}','至少 n 次'),
    ('{n,m}','n 到 m 次'),
    ('字符类','h'),
    ('[abc]','匹配 a 或 b 或 c'),
    ('[^abc]','匹配非 a/b/c'),
    ('[a-z]','匹配 a 到 z'),
    ('[0-9]','匹配 0 到 9'),
    ('[a-zA-Z0-9]','字母和数字'),
    ('分组与引用','h'),
    ('(abc)','捕获组'),
    ('(?:abc)','非捕获组'),
    ('(?<name>abc)','命名捕获组'),
    ('\\1','反向引用第1组'),
    ('前瞻与后顾','h'),
    ('(?=abc)','正向前瞻(后面是abc)'),
    ('(?!abc)','负向前瞻(后面不是abc)'),
    ('(?<=abc)','正向后顾(前面是abc)'),
    ('(?<!abc)','负向后顾(前面不是abc)'),
    ('锚点','h'),
    ('^','行首'),
    ('$','行尾'),
    ('\\b','单词边界'),
    ('\\B','非单词边界'),
    ('标志/修饰符','h'),
    ('/pattern/i','忽略大小写'),
    ('/pattern/g','全局匹配'),
    ('/pattern/m','多行模式'),
    ('/pattern/s','点号匹配换行'),
    ('常用验证模式','h'),
    ('^[\\w.-]+@[\\w.-]+\\.\\w+$','邮箱验证'),
    ('^1[3-9]\\d{9}$','中国大陆手机号'),
    ('^(?=.*[A-Z])(?=.*\\d).{8,}$','密码(大写+数字+8位)'),
    ('^(https?:\\/\\/)[\\w.-]+','URL验证'),
    ('^\\d{4}-\\d{2}-\\d{2}$','日期 YYYY-MM-DD'),
    ('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$','十六进制颜色值'),
    ('^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$','IPv4地址'),
    ('常用提取模式','h'),
    ('https?://[^\\s]+','提取URL'),
    ('\\b[A-Za-z0-9._%+-]+@[^\\s@]+','提取邮箱'),
    ('\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b','提取IP地址'),
    ('<([a-z]+)[^>]*>(.*?)<\\/\\1>','匹配HTML标签'),
]

# ── Python 速查 ───────────────────────────────────────────
PYTHON = [
    ('数据类型','h'),
    ('int, float, str, bool','基本类型'),
    ('list, tuple, set, dict','集合类型'),
    ('None','空值'),
    ('bytes, bytearray','字节类型'),
    ('字符串操作','h'),
    ('s.split(",")','分割字符串'),
    ('",".join(list)','合并列表'),
    ('s.strip()','去除首尾空白'),
    ('s.replace("a","b")','替换'),
    ('s.startswith("x")','前缀判断'),
    ('s.endswith(".py")','后缀判断'),
    ('s.upper(), s.lower()','大小写转换'),
    ('s.find("sub")','查找子串位置'),
    ('s.count("x")','计数'),
    ('f"Hello {name}"','格式化字符串(f-string)'),
    ('f"值={val:.2f}"','格式化数字'),
    ('列表操作','h'),
    ('[x for x in list if cond]','列表推导式'),
    ('sorted(list, key=lambda x: x)','排序'),
    ('list.append(x)','添加元素'),
    ('list.extend(list2)','扩展列表'),
    ('list.pop()','弹出末尾'),
    ('list.insert(0, x)','头部插入'),
    ('list.index(x)','查找元素位置'),
    ('list.reverse()','反转列表'),
    ('list[::2]','步长切片'),
    ('list[-1]','最后一个元素'),
    ('字典操作','h'),
    ('d.get("key", default)','安全取值'),
    ('d.keys(), d.values(), d.items()','键值对'),
    ('{k: v for k, v in items}','字典推导式'),
    ('d.setdefault("key", val)','设置默认值'),
    ('d.update({"k": "v"})','合并字典'),
    ('d.pop("key", None)','安全删除'),
    ('集合操作','h'),
    ('set1 | set2','并集'),
    ('set1 & set2','交集'),
    ('set1 - set2','差集'),
    ('set1 ^ set2','对称差集'),
    ('文件操作','h'),
    ('open("f","r").read()','读取文件'),
    ('with open("f","w") as fp: fp.write(x)','写入文件'),
    ('pathlib.Path("f").read_text()','Path 读取'),
    ('pathlib.Path("f").write_text(x)','Path 写入'),
    ('pathlib.Path("f").exists()','检查存在'),
    ('pathlib.Path("d").mkdir(parents=True)','递归创建目录'),
    ('pathlib.Path.glob("*.py")','通配搜索'),
    ('装饰器','h'),
    ('@property','属性装饰器'),
    ('@staticmethod','静态方法'),
    ('@classmethod','类方法'),
    ('@functools.lru_cache','缓存装饰器'),
    ('@functools.wraps(fn)','保留函数元信息'),
    ('常用内置函数','h'),
    ('map(fn, iterable)','映射'),
    ('filter(fn, iterable)','过滤'),
    ('enumerate(iterable)','带索引遍历'),
    ('zip(list1, list2)','并行遍历'),
    ('any(iterable), all(iterable)','逻辑判断'),
    ('isinstance(x, type)','类型检查'),
    ('type(x)','获取类型'),
    ('len(x), min(x), max(x)','长度/最小/最大'),
    ('Type Hints 类型提示','h'),
    ('def fn(x: int) -> str:','函数类型标注'),
    ('list[int]','列表类型'),
    ('dict[str, int]','字典类型'),
    ('Optional[str]','可选类型(= str | None)'),
    ('Union[int, str]','联合类型'),
    ('tuple[int, ...]','可变元组'),
    ('from typing import TypedDict','类型化字典'),
    ('Dataclasses','h'),
    ('@dataclass','数据类装饰器'),
    ('@dataclass(frozen=True)','不可变数据类'),
    ('field(default_factory=list)','可变默认值'),
    ('dataclasses.asdict(obj)','转为字典'),
    ('dataclasses.astuple(obj)','转为元组'),
    ('async/await 异步编程','h'),
    ('async def fn():','定义异步函数'),
    ('await asyncio.sleep(1)','等待异步操作'),
    ('asyncio.run(main())','运行异步主函数'),
    ('asyncio.gather(t1, t2)','并发运行'),
    ('async with aiohttp.ClientSession():','异步HTTP会话'),
    ('async for item in async_iter():','异步迭代'),
    ('itertools','h'),
    ('itertools.chain(a, b)','链接迭代器'),
    ('itertools.product(a, b)','笛卡尔积'),
    ('itertools.permutations(s)','排列'),
    ('itertools.combinations(s, r)','组合'),
    ('itertools.groupby(data, key)','分组'),
    ('itertools.islice(iter, n)','取前n个'),
    ('contextlib','h'),
    ('@contextmanager','上下文管理器装饰器'),
    ('contextlib.suppress(Err)','忽略指定异常'),
    ('contextlib.redirect_stdout(f)','重定向标准输出'),
]

# ── VS Code 快捷键 ───────────────────────────────────────
VSCODE = [
    ('编辑','h'),
    ('Ctrl+X / Ctrl+C','剪切/复制当前行'),
    ('Alt+Up/Down','移动当前行'),
    ('Shift+Alt+Up/Down','复制当前行'),
    ('Ctrl+/','切换行注释'),
    ('Ctrl+Shift+/','切换块注释'),
    ('Ctrl+Shift+K','删除行'),
    ('Tab / Shift+Tab','缩进/反缩进'),
    ('Ctrl+] / Ctrl+[','缩进/反缩进'),
    ('Ctrl+Shift+[','折叠代码块'),
    ('Ctrl+Shift+]','展开代码块'),
    ('Ctrl+K Ctrl+0','折叠所有'),
    ('Ctrl+K Ctrl+J','展开所有'),
    ('导航','h'),
    ('Ctrl+P','快速打开文件'),
    ('Ctrl+Shift+P','命令面板'),
    ('Ctrl+G','跳转到行'),
    ('Ctrl+T','跳转到符号'),
    ('Ctrl+Shift+O','跳转到文件中的符号'),
    ('F12','跳转到定义'),
    ('Alt+F12','预览定义'),
    ('Shift+F12','查找所有引用'),
    ('Ctrl+Shift+F12','查看实现'),
    ('Ctrl+Tab','切换标签页'),
    ('Ctrl+\\','分屏'),
    ('Ctrl+1/2/3','切换编辑器组'),
    ('搜索与替换','h'),
    ('Ctrl+F','查找'),
    ('Ctrl+H','替换'),
    ('Ctrl+Shift+F','全局搜索'),
    ('F3 / Shift+F3','下一个/上一个匹配'),
    ('Alt+Enter','选择所有匹配项'),
    ('Ctrl+D','选择下一个相同词'),
    ('终端','h'),
    ('Ctrl+`','打开/关闭终端'),
    ('Ctrl+Shift+`','新建终端'),
    ('Ctrl+Shift+C','复制选择到终端'),
    ('Ctrl+Shift+V','粘贴到终端'),
    ('终端内 Ctrl+L','清屏'),
    ('终端内 Ctrl+C','中断当前命令'),
    ('调试','h'),
    ('F5','启动/继续调试'),
    ('Shift+F5','停止调试'),
    ('F9','切换断点'),
    ('Ctrl+Shift+F9','删除所有断点'),
    ('F10','单步跳过(Step Over)'),
    ('F11','单步进入(Step Into)'),
    ('Shift+F11','单步跳出(Step Out)'),
    ('Ctrl+Shift+F5','重启调试'),
    ('Ctrl+Shift+D','打开调试面板'),
    ('调试控制台','h'),
    ('Ctrl+Shift+Y','打开调试控制台'),
    ('条件断点: 右键断点','设置命中条件'),
    ('日志断点: 右键断点','不中断只输出日志'),
    ('数据断点','数据变化时中断'),
    ('多光标','h'),
    ('Alt+Click','添加光标'),
    ('Ctrl+Alt+Up/Down','上下添加光标'),
    ('Ctrl+D','选择下一个相同词'),
    ('Ctrl+Shift+L','选择所有相同词'),
    ('Ctrl+U','撤销上次光标操作'),
    ('Alt+Shift+I','在选区每行末尾添加光标'),
    ('代码操作','h'),
    ('Ctrl+.','快速修复(灯泡)'),
    ('Ctrl+Shift+M','查看问题面板'),
    ('Ctrl+K Ctrl+F','格式化选中代码'),
    ('Shift+Alt+F','格式化文档'),
    ('Ctrl+K Ctrl+C','添加行注释'),
    ('F2','重命名符号'),
    ('Ctrl+Shift+R','重构'),
    ('常用扩展','h'),
    ('ESLint','JS/TS 代码检查'),
    ('Prettier','代码格式化'),
    ('GitLens','Git 增强'),
    ('Error Lens','行内错误显示'),
    ('Todo Tree','TODO/FIXME 高亮'),
    ('Thunder Client','API 测试'),
    ('Remote SSH','远程开发'),
    ('Docker','Docker 管理'),
]

# ── Markdown 语法 ─────────────────────────────────────────
MARKDOWN = [
    ('标题','h'),
    ('# H1  ## H2  ### H3','一至六级标题'),
    ('--- 或 *** 或 ___','分隔线(水平线)'),
    ('文本样式','h'),
    ('**粗体**','粗体文本'),
    ('*斜体*','斜体文本'),
    ('***粗斜体***','粗斜体'),
    ('~~删除线~~','删除线'),
    ('`行内代码`','行内代码'),
    ('> 引用','引用块'),
    ('>> 嵌套引用','嵌套引用'),
    ('列表','h'),
    ('- 项目','无序列表'),
    ('* 项目','无序列表(星号)'),
    ('1. 项目','有序列表'),
    ('  - 嵌套','嵌套列表(缩进)'),
    ('- [ ] 任务','未完成任务'),
    ('- [x] 任务','已完成任务'),
    ('链接与图片','h'),
    ('[文本](url)','链接'),
    ('[文本](url "title")','带标题的链接'),
    ('![alt](url)','图片'),
    ('[ref]: url','引用式链接定义'),
    ('[文本][ref]','引用式链接'),
    ('代码','h'),
    ('```语言\\n代码\\n```','代码块'),
    ('~~~语言\\n代码\\n~~~','代码块(波浪线)'),
    ('`行内代码`','行内代码'),
    ('```diff','diff 高亮代码块'),
    ('表格','h'),
    ('| 列1 | 列2 |','表头'),
    ('|:----|----:|','左对齐/右对齐'),
    ('|:---:|','居中对齐'),
    ('| 数据 | 数据 |','数据行'),
    ('扩展语法','h'),
    ('# 标题 {#id}','自定义ID(扩展)'),
    ('[TOC]','目录(部分解析器)'),
    ('==高亮文本==','高亮文本(扩展)'),
    ('脚注[^1] 和 [^1]: 说明','脚注'),
    ('Mermaid 图表','h'),
    ('```mermaid','Mermaid 代码块'),
    ('graph TD','流程图(上到下)'),
    ('graph LR','流程图(左到右)'),
    ('sequenceDiagram','时序图'),
    ('classDiagram','类图'),
    ('stateDiagram-v2','状态图'),
    ('pie title 标题','饼图'),
    ('gantt','甘特图'),
    ('emoji','h'),
    (':smile: :heart: :rocket:','常用emoji短码'),
    (':+1: :check: :warning:','表情/符号'),
    (':fire: :star: :bug:','技术常用emoji'),
    ('HTML 嵌入','h'),
    ('<details><summary>标题</summary>内容</details>','可折叠内容'),
    ('<kbd>Ctrl</kbd>+<kbd>C</kbd>','键盘按键样式'),
    ('<br>','换行'),
    ('<sup>上标</sup> <sub>下标</sub>','上下标'),
]

# ── Linux 命令速查 ────────────────────────────────────────
LINUX = [
    ('文件操作','h'),
    ('ls -la','列出文件(含隐藏)'),
    ('ls -lhS','按大小排序'),
    ('ls -lhtr','按时间倒序'),
    ('cd <dir>','切换目录'),
    ('cd -','回到上一个目录'),
    ('pwd','当前目录'),
    ('cp -r <src> <dst>','递归复制'),
    ('cp -a <src> <dst>','归档复制(保留属性)'),
    ('mv <src> <dst>','移动/重命名'),
    ('rm -rf <dir>','强制递归删除'),
    ('mkdir -p <dir>','递归创建目录'),
    ('touch <file>','创建空文件/更新时间戳'),
    ('ln -s <target> <link>','创建软链接'),
    ('find <path> -name "*.py"','按名查找文件'),
    ('find <path> -size +100M','按大小查找'),
    ('find <path> -mtime -7','7天内修改的文件'),
    ('find <path> -exec cmd {} \\;','对结果执行命令'),
    ('文本处理','h'),
    ('cat <file>','查看文件'),
    ('less <file>','分页查看'),
    ('head -n 20 <file>','查看前20行'),
    ('tail -f <file>','实时查看'),
    ('tail -n 100 <file>','查看最后100行'),
    ('grep "pattern" <file>','搜索文本'),
    ('grep -r "pattern" <dir>','递归搜索'),
    ('grep -i "pattern" <file>','忽略大小写'),
    ('grep -n "pattern" <file>','显示行号'),
    ('grep -c "pattern" <file>','统计匹配行数'),
    ('grep -v "pattern" <file>','反向匹配'),
    ('grep -A 3 -B 3 "p" <file>','显示前后3行'),
    ('sed "s/old/new/g" <file>','替换文本'),
    ('sed -i "s/old/new/g" <file>','原地替换'),
    ('sed -n "10,20p" <file>','打印第10-20行'),
    ('awk "{print $1}" <file>','提取列'),
    ('awk -F: "{print $1}" <file>','指定分隔符'),
    ('awk "{sum+=$1} END{print sum}" <f>','列求和'),
    ('sort <file>','排序'),
    ('sort -u <file>','排序去重'),
    ('uniq -c <file>','统计重复行'),
    ('wc -l <file>','统计行数'),
    ('cut -d: -f1 <file>','按分隔符切字段'),
    ('tr "a-z" "A-Z"','字符转换'),
    ('权限管理','h'),
    ('chmod 755 <file>','设置权限(rwxr-xr-x)'),
    ('chmod u+x <file>','添加执行权限'),
    ('chmod -R 644 <dir>','递归设置权限'),
    ('chown user:group <file>','修改所有者'),
    ('chown -R user:group <dir>','递归修改所有者'),
    ('进程管理','h'),
    ('ps aux','列出所有进程'),
    ('ps aux | grep <name>','查找进程'),
    ('top','实时进程监控'),
    ('htop','增强版进程监控'),
    ('kill -9 <pid>','强制杀进程'),
    ('kill -15 <pid>','优雅终止进程'),
    ('killall <name>','按名称杀进程'),
    ('pkill -f "pattern"','按模式杀进程'),
    ('nohup cmd &','后台运行'),
    ('bg / fg','后台/前台切换'),
    ('jobs','列出后台任务'),
    ('systemctl','h'),
    ('systemctl start <svc>','启动服务'),
    ('systemctl stop <svc>','停止服务'),
    ('systemctl restart <svc>','重启服务'),
    ('systemctl status <svc>','查看服务状态'),
    ('systemctl enable <svc>','开机自启'),
    ('systemctl disable <svc>','取消开机自启'),
    ('systemctl list-units --type=service','列出所有服务'),
    ('systemctl daemon-reload','重载systemd配置'),
    ('journalctl','h'),
    ('journalctl -u <svc>','查看服务日志'),
    ('journalctl -u <svc> -f','实时跟踪服务日志'),
    ('journalctl --since "1 hour ago"','最近1小时日志'),
    ('journalctl -p err','只看错误级别'),
    ('journalctl --disk-usage','日志占用空间'),
    ('网络','h'),
    ('curl <url>','HTTP 请求'),
    ('curl -o file <url>','下载保存为文件'),
    ('curl -X POST -d "data" <url>','POST请求'),
    ('curl -H "Header: val" <url>','自定义请求头'),
    ('wget <url>','下载文件'),
    ('wget -c <url>','断点续传'),
    ('ping <host>','测试连通性'),
    ('ss -tlnp','查看监听端口(ss替代netstat)'),
    ('netstat -tlnp','查看监听端口'),
    ('ip addr show','查看IP地址'),
    ('ip route show','查看路由表'),
    ('nslookup <domain>','DNS查询'),
    ('dig <domain>','DNS查询(详细)'),
    ('traceroute <host>','路由追踪'),
    ('ssh user@host','SSH 连接'),
    ('ssh -p 2222 user@host','指定端口SSH'),
    ('ssh -i key.pem user@host','指定密钥SSH'),
    ('scp file user@host:/path','SCP上传'),
    ('scp user@host:/path file','SCP下载'),
    ('rsync -avz src/ dst/','增量同步'),
    ('rsync -avz --delete src/ dst/','同步(删除目标多余)'),
    ('rsync -avz -e ssh src/ user@h:dst/','远程同步'),
    ('SSH 配置','h'),
    ('~/.ssh/config','SSH 配置文件'),
    ('Host myserver','主机别名定义'),
    ('  HostName 192.168.1.1','主机地址'),
    ('  User admin','登录用户'),
    ('  Port 2222','端口'),
    ('  IdentityFile ~/.ssh/key','密钥文件'),
    ('Crontab 定时任务','h'),
    ('crontab -e','编辑定时任务'),
    ('crontab -l','列出定时任务'),
    ('* * * * * cmd','分 时 日 月 周 命令'),
    ('0 2 * * * cmd','每天凌晨2点'),
    ('*/5 * * * * cmd','每5分钟'),
    ('0 0 * * 0 cmd','每周日零点'),
    ('压缩解压','h'),
    ('tar -czf archive.tar.gz <dir>','压缩(gzip)'),
    ('tar -xzf archive.tar.gz','解压(gzip)'),
    ('tar -xjf archive.tar.bz2','解压(bzip2)'),
    ('tar -xf archive.tar','解压(自动检测)'),
    ('zip -r archive.zip <dir>','ZIP 压缩'),
    ('unzip archive.zip','ZIP 解压'),
    ('gzip <file>','GZIP 压缩'),
    ('gunzip <file>.gz','GZIP 解压'),
    ('系统信息','h'),
    ('uname -a','内核信息'),
    ('df -h','磁盘使用'),
    ('du -sh <dir>','目录大小'),
    ('free -h','内存使用'),
    ('uptime','运行时间和负载'),
    ('whoami','当前用户'),
    ('last','登录历史'),
]

# ── Kubernetes (K8S) 速查 ─────────────────────────────────
K8S = [
    ('集群信息','h'),
    ('kubectl cluster-info','查看集群信息'),
    ('kubectl get nodes','列出节点'),
    ('kubectl get nodes -o wide','节点详情'),
    ('kubectl describe node <name>','节点详情'),
    ('kubectl top nodes','节点资源使用'),
    ('kubectl version','查看版本'),
    ('kubectl config use-context <ctx>','切换集群上下文'),
    ('kubectl config get-contexts','列出上下文'),
    ('Pod 操作','h'),
    ('kubectl get pods','列出Pod(当前namespace)'),
    ('kubectl get pods -A','列出所有namespace的Pod'),
    ('kubectl get pods -o wide','Pod详情(IP/节点)'),
    ('kubectl get pods -l app=nginx','按标签过滤'),
    ('kubectl describe pod <name>','查看Pod详情'),
    ('kubectl logs <pod>','查看Pod日志'),
    ('kubectl logs -f <pod>','实时查看日志'),
    ('kubectl logs <pod> -c <ctr>','查看指定容器日志'),
    ('kubectl logs --previous <pod>','查看上次崩溃日志'),
    ('kubectl exec -it <pod> -- /bin/sh','进入Pod'),
    ('kubectl exec -it <pod> -c <ctr> -- sh','进入指定容器'),
    ('kubectl port-forward <pod> 8080:80','端口转发'),
    ('kubectl delete pod <name>','删除Pod'),
    ('kubectl get pod <name> -o yaml','输出Pod YAML'),
    ('kubectl run <name> --image=<img>','创建Pod'),
    ('Deployment','h'),
    ('kubectl get deployments','列出Deployment'),
    ('kubectl describe deploy <name>','查看Deployment详情'),
    ('kubectl create deploy <name> --image=<img>','创建Deployment'),
    ('kubectl apply -f deploy.yaml','应用配置文件'),
    ('kubectl edit deploy <name>','在线编辑'),
    ('kubectl scale deploy <name> --replicas=3','扩容'),
    ('kubectl set image deploy/<name> <ctr>=<img>','更新镜像'),
    ('kubectl rollout status deploy/<name>','查看滚动状态'),
    ('kubectl rollout history deploy/<name>','查看历史版本'),
    ('kubectl rollout undo deploy/<name>','回滚到上一版本'),
    ('kubectl rollout undo deploy/<name> --to-revision=2','回滚到指定版本'),
    ('kubectl rollout restart deploy/<name>','重启Pod'),
    ('kubectl delete deploy <name>','删除Deployment'),
    ('Service','h'),
    ('kubectl get svc','列出Service'),
    ('kubectl describe svc <name>','查看Service详情'),
    ('kubectl expose deploy <name> --port=80','暴露Deployment'),
    ('kubectl expose deploy <name> --type=LoadBalancer','负载均衡'),
    ('kubectl delete svc <name>','删除Service'),
    ('ConfigMap & Secret','h'),
    ('kubectl get configmap','列出ConfigMap'),
    ('kubectl create configmap <name> --from-file=<f>','从文件创建'),
    ('kubectl create configmap <name> --from-literal=k=v','从KV创建'),
    ('kubectl get secrets','列出Secret'),
    ('kubectl create secret generic <n> --from-literal=k=v','创建Secret'),
    ('kubectl get secret <name> -o yaml','查看Secret(base64)'),
    ('Namespace','h'),
    ('kubectl get ns','列出Namespace'),
    ('kubectl create ns <name>','创建Namespace'),
    ('kubectl config set-context --current --namespace=<ns>','切换默认NS'),
    ('kubectl delete ns <name>','删除Namespace'),
    ('其他资源','h'),
    ('kubectl get all','列出所有资源'),
    ('kubectl get events --sort-by=.metadata.creationTimestamp','按时间排序事件'),
    ('kubectl api-resources','列出API资源类型'),
    ('kubectl explain <resource>','查看资源定义'),
    ('kubectl diff -f <file>','对比配置差异'),
    ('kubectl top pods','Pod资源使用'),
    ('kubectl cordon <node>','标记节点不可调度'),
    ('kubectl uncordon <node>','恢复节点调度'),
    ('kubectl drain <node>','排空节点'),
    ('kubectl taint nodes <n> k=v:NoSchedule','设置污点'),
]

# ── PowerShell 速查 ───────────────────────────────────────
POWERSHELL = [
    ('基础命令','h'),
    ('Get-Command','列出所有命令'),
    ('Get-Command -Name *<keyword>*','按关键字搜索命令'),
    ('Get-Help <cmd>','查看帮助'),
    ('Get-Help <cmd> -Full','完整帮助'),
    ('Get-Help <cmd> -Examples','示例'),
    ('Get-Member','查看对象成员'),
    ('Update-Help','更新帮助文件'),
    ('文件与目录','h'),
    ('Get-ChildItem (ls)','列出文件'),
    ('Get-ChildItem -Recurse','递归列出'),
    ('Get-ChildItem -Hidden','含隐藏文件'),
    ('Set-Location (cd)','切换目录'),
    ('New-Item -ItemType File <path>','创建文件'),
    ('New-Item -ItemType Directory <path>','创建目录'),
    ('Remove-Item (rm)','删除'),
    ('Copy-Item (cp)','复制'),
    ('Move-Item (mv)','移动/重命名'),
    ('Rename-Item','重命名'),
    ('Get-Content (cat)','读取文件'),
    ('Get-Content <f> -Tail 20','查看最后20行'),
    ('Get-Content <f> -Wait','实时查看(= tail -f)'),
    ('Set-Content','写入文件'),
    ('Add-Content','追加到文件'),
    ('Select-String (grep)','搜索文本'),
    ('管道与对象','h'),
    ('| Where-Object { $_.Prop -eq "val" }','过滤'),
    ('| Select-Object Name, Size','选择属性'),
    ('| Select-Object -First 10','取前10'),
    ('| Select-Object -Last 10','取后10'),
    ('| Sort-Object Name','排序'),
    ('| Sort-Object Name -Descending','降序排序'),
    ('| ForEach-Object { $_.Name }','遍历处理'),
    ('| Measure-Object','统计(计数/总和等)'),
    ('| Group-Object','分组'),
    ('| Format-Table','表格格式化'),
    ('| Format-List','列表格式化'),
    ('| Tee-Object -FilePath f.txt','输出到屏幕和文件'),
    ('进程管理','h'),
    ('Get-Process','列出进程'),
    ('Get-Process -Name <name>','按名称查找'),
    ('Stop-Process -Name <name>','按名称停止'),
    ('Stop-Process -Id <pid>','按PID停止'),
    ('Start-Process <cmd>','启动进程'),
    ('Start-Process <cmd> -Verb RunAs','以管理员运行'),
    ('网络','h'),
    ('Test-Connection <host>','测试连通性(=ping)'),
    ('Test-NetConnection <host> -Port <p>','测试端口'),
    ('Invoke-WebRequest <url>','HTTP请求'),
    ('Invoke-RestMethod <url>','REST API调用'),
    ('Get-NetIPAddress','查看IP地址'),
    ('Get-NetTCPConnection','查看TCP连接'),
    ('系统信息','h'),
    ('Get-ComputerInfo','系统详细信息'),
    ('Get-Host','主机信息'),
    ('Get-Date','当前日期时间'),
    ('Get-Service','列出服务'),
    ('Get-Service -Name <name>','查看指定服务'),
    ('Start-Service <name>','启动服务'),
    ('Stop-Service <name>','停止服务'),
    ('Restart-Service <name>','重启服务'),
    ('Get-EventLog -LogName System -Newest 20','最近20条系统日志'),
    ('注册表','h'),
    ('Get-ItemProperty <path>','读取注册表'),
    ('Set-ItemProperty <path> <name> <val>','设置注册表值'),
    ('New-Item <path>','创建注册表项'),
    ('Remove-Item <path>','删除注册表项'),
    ('HKLM:\\SOFTWARE\\...','本地机器注册表'),
    ('HKCU:\\...','当前用户注册表'),
    ('变量与类型','h'),
    ('$var = "value"','定义变量'),
    ('[int]$num = 42','强类型变量'),
    ('$arr = @(1, 2, 3)','数组'),
    ('$hash = @{k="v"}','哈希表'),
    ('$null -eq $var','空值检查'),
    ('"Hello $name"','字符串插值'),
    ('"值=$($obj.Prop)"','表达式插值'),
    ('控制流','h'),
    ('if () {} elseif () {} else {}','条件分支'),
    ('switch ($val) { "a" {} default {} }','Switch'),
    ('foreach ($x in $list) {}','ForEach循环'),
    ('for ($i=0; $i -lt 10; $i++) {}','For循环'),
    ('while ($cond) {}','While循环'),
    ('try {} catch {} finally {}','异常处理'),
    ('函数','h'),
    ('function fn($param) { ... }','定义函数'),
    ('function fn { param([string]$x) }','带类型参数'),
    ('[CmdletBinding()] param()','高级函数'),
    ('return $value','返回值'),
    ('模块','h'),
    ('Get-Module -ListAvailable','列出可用模块'),
    ('Import-Module <name>','导入模块'),
    ('Install-Module <name> -Scope CurrentUser','安装模块'),
    ('Update-Module <name>','更新模块'),
    ('别名','h'),
    ('Get-Alias','列出所有别名'),
    ('Set-Alias <name> <cmd>','创建别名'),
    ('New-Alias <name> <cmd> -Scope Global','全局别名'),
    ('配置文件','h'),
    ('$PROFILE','配置文件路径'),
    ('$PROFILE.AllUsersAllHosts','全局配置路径'),
    ('Test-Path $PROFILE','检查配置文件是否存在'),
    ('notepad $PROFILE','编辑配置文件'),
]

# ── 菜单 ──────────────────────────────────────────────────
SHEETS = [
    ('1','Git 速查',       GIT),
    ('2','Docker 速查',    DOCKER),
    ('3','NPM/Yarn 速查',  NPM),
    ('4','正则表达式速查',  REGEX),
    ('5','Python 速查',    PYTHON),
    ('6','VS Code 快捷键', VSCODE),
    ('7','Markdown 语法',  MARKDOWN),
    ('8','Linux 命令速查',  LINUX),
    ('9','Kubernetes 速查',K8S),
    ('0','PowerShell 速查',POWERSHELL),
]

def cheatsheet_menu():
    while True:
        clear()
        console.print(Align.center(Text("  ═══  HYPERVOID 速查表  ═══  ", style=T.ACCENT)))
        console.print()
        for key, name, _ in SHEETS:
            console.print(f"  [{T.KEY}][{key}][/] [{T.LABEL}]{name}[/]")
        console.print()
        console.print(f"  [{T.DIM}]选择速查表  Esc 返回[/]")
        console.print(f"  [{T.DIM}]hypervoid.top[/]")

        kt,k = read_key()
        if kt=='esc' or (kt=='char' and k=='q'): return
        if kt=='char' and k in [str(i) for i in range(10)]:
            idx_map = {'1':0,'2':1,'3':2,'4':3,'5':4,'6':5,'7':6,'8':7,'9':8,'0':9}
            if k in idx_map:
                idx = idx_map[k]
                if idx < len(SHEETS):
                    _,name,data = SHEETS[idx]
                    scroll_view(name, fmt(data))

if __name__ == '__main__':
    cheatsheet_menu()
